version: '3'

services:
  app:
    container_name: python
    build: .
    ports:
      - 8000:8000
    environment:
      POSTGRES_PASSWORD:
    tty:
      true
    volumes:
      # - ./app:/root/opt
      - .:/app

    # command: fresh  # 常にONでいいかは微妙


  # nginx でルーティングさせる
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - apii
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   environment:
  #     - TZ=Asia/Tokyo
  #   volumes:
  #     - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
