version: '3'

services:
  app:
    container_name: app
    build: ./docker/backend
    ports:
      - 8000:8000
    tty:
      true
    volumes:
      - .:/app

  front:
    container_name: front
    build: ./docker/frontend
    ports:
      - 3000:3000
    tty:
      true
    volumes:
      - .:/app
    command: /bin/sh
